### PR TITLE
#87 

### PR DESCRIPTION
**Pull request by ejboettcher**
Resolved issue #87
-  [x]  Removed bower
-  [x] Updated npm config file for latest leaflet versions
-  [x] Updated README.md to only include npm workflow

### CODE REVIEW

**Comment by DavidEBest** [comment]
The switches from h4 to h3 and h2 to h1 made the text larger. Could you make those smaller with some CSS?

**Comment by ejboettcher** [comment]
I think so.  The HTML Code sniffer I was using flagged how the headers were number for ADA compliance.  

I should be able to change the size in css.  Will take a look at it this week.

The ADA changes were supposed to be a PR but, it was pulled into this one automatically.

**Comment by DavidEBest** [comment]
Something like:

```
h1 {
font-size: 1.5em;
}

.FAQ-item h3 {
    margin: 0rem;
    margin-left: .5rem;
    margin-right: .5rem;
    font-size: 1em;
    font-weight: bold;
}
```

Should do it.

**Comment by ejboettcher** [comment]
- [x] Change Font size.

**Comment by DavidEBest** [comment]
Great, thanks!

**Comment by DavidEBest** [comment]
If you were interested in another PR, you could make the same changes in the MCLotLinker repo. It's almost the same code - it's the county's Land Bank version of the site.

**Pull request merged**
