### PR TITLE
Slimming reaps file and including node script

### PR DESCRIPTION
**Pull request by dane-king**
I wrote a script to parse the file using node, so it can be modified and reparsed in the future.

### CODE REVIEW

**Comment by DavidEBest** [comment]
Great, @dane-king! I'll test & merge this in later today.

**Comment by dane-king** [comment]
Sorry about that, the issues should be fixed now, let me know if there is anything else

**Comment by dane-king** [comment]
Another thing I just created the file, I noticed that you have a var points=[] and they code to calls it is  a.locationdata.longitude, so the file needs to change or the lookup. It still seems to have some issues I am looking at, can I work on integrating the new file into the main.js?

**Comment by DavidEBest** [comment]
Sure. The main.js file will need to be updated to use the `a.longitude` & `a.latitude`. The reap file processing is still very much a manual process. We will hoping to work on automating this process this weekend. For more context, the reaps file is initially generated by the https://github.com/codefordayton/scrapers project.

**Pull request closed without merging**
