### PR TITLE
Add a filter to show newly added properties.

### PR DESCRIPTION
**Pull request by LukeKuenneke**
https://github.com/codefordayton/daytonreap/issues/76

### CODE REVIEW

**Comment by itopaloglu83** [comment]
Luke, so how this work exactly?

**Comment by LukeKuenneke** [comment]
Looks like I forgot to add the updated index.html file in that first commit.

**Comment by DavidEBest** [comment]
@LukeKuenneke Is this good for review?

**Comment by LukeKuenneke** [comment]
Should be, I checked in the missing changes to the index.html file.

**Comment by DavidEBest** [comment]
:shipit:

**Comment by DavidEBest** [comment]
Merged... I'll deploy the code tomorrow evening.

**Comment by LukeKuenneke** [comment]
Aww yeah, my first Code for Dayton PR got merged.

**Pull request merged**
